### ISSUE TITLE
是否安装C#环境？

### ISSUE THREAD

**Issue by nmybk** [liuke-wuhan/ZuAnBot#11]
您好，是否需要安装C#环境呢？

**Comment by liuke-wuhan** [comment]
> 您好，是否需要安装C#环境呢？

不需要，软件也是免安装的

**Comment by nmybk** [comment]
具体怎么使用呢？下载好资源包后，启动不了呀，是要把安装包放在游戏目录下吗？

**Comment by liuke-wuhan** [comment]
> 具体怎么使用呢？下载好资源包后，启动不了呀，是要把安装包放在游戏目录下吗？

安装.net framework 4.7.2运行时试一试
https://dotnet.microsoft.com/zh-cn/download/dotnet-framework/net472
