### ISSUE TITLE
如何只用caiHONGPI.json的文件

### ISSUE THREAD

**Issue by Syf24680** [liuke-wuhan/ZuAnBot#12]
我发现这个文件里面的内容都是夸人的
我要如何才能一直夸别人呢？

**Comment by liuke-wuhan** [comment]
> 我发现这个文件里面的内容都是夸人的 我要如何才能一直夸别人呢？

被你发现了，最开始有夸人的功能，现在取消了。等我有空把词库做成独立的吧，这样就可以灵活使用了
