### ISSUE TITLE
本地词库能不能独立出来，自己配置，建议添加一个喷情侣词库

### ISSUE THREAD

**Issue by oDaShuTz** [liuke-wuhan/ZuAnBot#3]
妹子菜男的狂护，气死我了

**Comment by liuke-wuhan** [comment]
我本来为了软件免安装，把所有文件都集成在一个exe了所以将本地词库也揉了进去。不过可以做一个读取指定txt文件的功能，喷情侣的词库我可以找一找，现在的词库也是网上搜罗的，毕竟我要有喷人的本事也不会写这个小东西了= =
