### ISSUE TITLE
狂喷功能可以改为一句一字发送,这样就不会被屏蔽,并缩短狂喷句子的长度

### ISSUE THREAD

**Issue by 2776** [liuke-wuhan/ZuAnBot#4]

**Comment by oDaShuTz** [comment]
或者每个字中夹杂那种不可识别的字符（韩文或者日文），聊天框里显示不出来，而且检测不到。

现在轻喷即使发多了，也会被检测出来的。

**Comment by liuke-wuhan** [comment]
狂喷语录里面有一些肯定会屏蔽的字，即使一个也会被屏蔽

**Comment by liuke-wuhan** [comment]
> 或者每个字中夹杂那种不可识别的字符（韩文或者日文），聊天框里显示不出来，而且检测不到。
> 
> 现在轻喷即使发多了，也会被检测出来的。

轻喷中有一些没有测试出来，还是会被屏蔽，用我最新的release应该没问题
