### ISSUE TITLE
如何发送中文的

### ISSUE THREAD

**Issue by 4379711** [liuke-wuhan/ZuAnBot#6]
因为我不懂C#,看下你的代码,没看明白是如何把中文通过按键转换的

**Comment by 4379711** [comment]
Simulate.Events().
                Click(WindowsInput.Events.KeyCode.Enter).Wait(75).
                Click(word).Wait(75).
                Click(WindowsInput.Events.KeyCode.Enter).
                Invoke();
                
                这个函数,它的底层逻辑是什么,调用了user32.dll哪个函数吗?

**Comment by liuke-wuhan** [comment]
Simulate.Events().
Click(WindowsInput.Events.KeyCode.Enter).Wait(75).
Click(word).Wait(75).
Click(WindowsInput.Events.KeyCode.Enter).
Invoke();

**Comment by liuke-wuhan** [comment]
> 
用一个库模拟键盘输入指定内容
Simulate.Events().
Click(WindowsInput.Events.KeyCode.Enter).Wait(75).//按下回车后等待75ms
Click(word).Wait(75).//输入垃圾话，等待75ms
Click(WindowsInput.Events.KeyCode.Enter).//按下回车
Invoke();
